default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME", "garagedom") %>
  password: <%= ENV.fetch("DB_PASSWORD", "garagedom") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>

development:
  <<: *default
  database: garagedom_api_development

test:
  <<: *default
  database: garagedom_api_test

production:
  primary:
    url: <%= ENV["DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  cache:
    url: <%= ENV["CACHE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    url: <%= ENV["QUEUE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    url: <%= ENV["CABLE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate
